
const Data = {
    data:[
        {
          id: 18,
          clientId: 2,
          createdDate: "2021-06-15T14:34:29.000Z",
          postEntities: [
            { id: 18, postId: 18, type: "CHALLENGE", entityId: 226, PostId: 18 },
          ],
          postFilters: [
            {
              id: 35,
              postId: 18,
              filterValue: "246696",
              filterType: "DEPARTMENT",
              PostId: 18,
            },
          ],
          postComments: [],
          postLikes: [
            {
              id: 27,
              postId: 18,
              createdDate: "2021-06-15T23:50:23.000Z",
              userId: 226,
            },
          ],
          type: "GOAL_REACH",
          metadata: {
            challenge: {
              challenge_id: 226,
              kpi_id: 43,
              client_id: 2,
              author: null,
              prize: 0,
              ctype: null,
              title: "fcr345",
              description:
                "salsa mix, merengue, bachata, cumbia and more for winners",
              start_date: "2021-06-15T08:32:59.000Z",
              end_date: "2021-06-15T08:35:59.000Z",
              joinPoints: null,
              winnerPoints: 345,
              cstatus: "1",
              thumbnail_image: null,
              createdAt: "2021-06-15T14:34:28.000Z",
              updatedAt: "2021-06-15T14:34:28.000Z",
              Users: [
                {
                  user_id: 136,
                  role_id: 3,
                  client_id: 2,
                  username: "pablo+agentuone@josoroma.com",
                  lastName: "Shore",
                  firstName: "Robert",
                  password: "12345678",
                  thirdPartyID: null,
                  integrationID: "396588",
                  cognitoIdentityId: "a18e93a0-0d97-4660-8a31-b7e9c6980d89",
                  profileImg: null,
                  pointsBalance: 8035,
                  pointsCumulative: 5500,
                  ustatus: null,
                  signon_ip: null,
                  signon_date: null,
                  last_ip: null,
                  last_login: null,
                  repTileBgImg: null,
                  badgesJSON: null,
                  teamJSON: null,
                  createdAt: null,
                  updatedAt: "2021-07-02T03:47:36.000Z",
                  enabled: true,
                  ChallengesUser: {
                    cd_id: 451,
                    challenge_id: 226,
                    participant_id: 136,
                    min_required: null,
                    score: null,
                    createdAt: "2021-06-15T14:34:28.000Z",
                    updatedAt: "2021-06-15T14:34:28.000Z",
                  },
                  USER_TO_DEPARTMENT: [
                    {
                      department_id: 246696,
                      dname: "Stratovize",
                      UserDepartment: {
                        ud_id: 97,
                        user_id: 136,
                        department_id: 246696,
                        created: null,
                        revoked: null,
                        createdAt: null,
                        updatedAt: null,
                      },
                    },
                  ],
                },
                {
                  user_id: 137,
                  role_id: 1,
                  client_id: 2,
                  username: "pablo+adminuone@josoroma.com",
                  lastName: "",
                  firstName: "BB5",
                  password: "12345678",
                  thirdPartyID: null,
                  integrationID: "6828607",
                  cognitoIdentityId: "82d0402c-1e7e-4410-bab6-968340aa5f65",
                  profileImg: null,
                  pointsBalance: 8968,
                  pointsCumulative: 2,
                  ustatus: null,
                  signon_ip: null,
                  signon_date: null,
                  last_ip: null,
                  last_login: null,
                  repTileBgImg: null,
                  badgesJSON: null,
                  teamJSON: null,
                  createdAt: null,
                  updatedAt: "2021-05-26T20:33:11.000Z",
                  enabled: true,
                  ChallengesUser: {
                    cd_id: 452,
                    challenge_id: 226,
                    participant_id: 137,
                    min_required: null,
                    score: null,
                    createdAt: "2021-06-15T14:34:28.000Z",
                    updatedAt: "2021-06-15T14:34:28.000Z",
                  },
                  USER_TO_DEPARTMENT: [
                    {
                      department_id: 246696,
                      dname: "Stratovize",
                      UserDepartment: {
                        ud_id: 98,
                        user_id: 137,
                        department_id: 246696,
                        created: null,
                        revoked: null,
                        createdAt: null,
                        updatedAt: "2021-02-22T16:27:09.000Z",
                      },
                    },
                  ],
                },
              ],
            },
          },
        },
        {
            id: 19,
            clientId: 2,
            createdDate: "2021-06-15T14:34:29.000Z",
            postEntities: [
              { id: 18, postId: 18, type: "CHALLENGE", entityId: 226, PostId: 18 },
            ],
            postFilters: [
              {
                id: 35,
                postId: 18,
                filterValue: "246696",
                filterType: "DEPARTMENT",
                PostId: 18,
              },
            ],
            postComments: [],
            postLikes: [
              {
                id: 27,
                postId: 18,
                createdDate: "2021-06-15T23:50:23.000Z",
                userId: 226,
              },
            ],
            type: "GOAL_REACH",
            metadata: {
              challenge: {
                challenge_id: 226,
                kpi_id: 43,
                client_id: 2,
                author: null,
                prize: 0,
                ctype: null,
                title: "fcr345",
                description:
                  "salsa mix, merengue, bachata, cumbia and more for winners",
                start_date: "2021-06-15T08:32:59.000Z",
                end_date: "2021-06-15T08:35:59.000Z",
                joinPoints: null,
                winnerPoints: 345,
                cstatus: "1",
                thumbnail_image: null,
                createdAt: "2021-06-15T14:34:28.000Z",
                updatedAt: "2021-06-15T14:34:28.000Z",
                Users: [
                  {
                    user_id: 136,
                    role_id: 3,
                    client_id: 2,
                    username: "pablo+agentuone@josoroma.com",
                    lastName: "Wick",
                    firstName: "John",
                    password: "12345678",
                    thirdPartyID: null,
                    integrationID: "396588",
                    cognitoIdentityId: "a18e93a0-0d97-4660-8a31-b7e9c6980d89",
                    profileImg: null,
                    pointsBalance: 8035,
                    pointsCumulative: 5500,
                    ustatus: null,
                    signon_ip: null,
                    signon_date: null,
                    last_ip: null,
                    last_login: null,
                    repTileBgImg: null,
                    badgesJSON: null,
                    teamJSON: null,
                    createdAt: null,
                    updatedAt: "2021-07-02T03:47:36.000Z",
                    enabled: true,
                    ChallengesUser: {
                      cd_id: 451,
                      challenge_id: 226,
                      participant_id: 136,
                      min_required: null,
                      score: null,
                      createdAt: "2021-06-15T14:34:28.000Z",
                      updatedAt: "2021-06-15T14:34:28.000Z",
                    },
                    USER_TO_DEPARTMENT: [
                      {
                        department_id: 246696,
                        dname: "Stratovize",
                        UserDepartment: {
                          ud_id: 97,
                          user_id: 136,
                          department_id: 246696,
                          created: null,
                          revoked: null,
                          createdAt: null,
                          updatedAt: null,
                        },
                      },
                    ],
                  },
                  {
                    user_id: 137,
                    role_id: 1,
                    client_id: 2,
                    username: "pablo+adminuone@josoroma.com",
                    lastName: "",
                    firstName: "FCR",
                    password: "12345678",
                    thirdPartyID: null,
                    integrationID: "6828607",
                    cognitoIdentityId: "82d0402c-1e7e-4410-bab6-968340aa5f65",
                    profileImg: null,
                    pointsBalance: 8968,
                    pointsCumulative: 2,
                    ustatus: null,
                    signon_ip: null,
                    signon_date: null,
                    last_ip: null,
                    last_login: null,
                    repTileBgImg: null,
                    badgesJSON: null,
                    teamJSON: null,
                    createdAt: null,
                    updatedAt: "2021-05-26T20:33:11.000Z",
                    enabled: true,
                    ChallengesUser: {
                      cd_id: 452,
                      challenge_id: 226,
                      participant_id: 137,
                      min_required: null,
                      score: null,
                      createdAt: "2021-06-15T14:34:28.000Z",
                      updatedAt: "2021-06-15T14:34:28.000Z",
                    },
                    USER_TO_DEPARTMENT: [
                      {
                        department_id: 246696,
                        dname: "Stratovize",
                        UserDepartment: {
                          ud_id: 98,
                          user_id: 137,
                          department_id: 246696,
                          created: null,
                          revoked: null,
                          createdAt: null,
                          updatedAt: "2021-02-22T16:27:09.000Z",
                        },
                      },
                    ],
                  },
                ],
              },
            },
          },
      ]
      
}


export default Data;